=== KngGroup/MySQLDataMigrator/src/ByDm/MySQLMigrateData/Resources/migration_configuration.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            elementFormDefault="qualified"
            >
    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            Author: Dmitry Bykov
            MySQL data migration schema
        </xsd:documentation>
    </xsd:annotation>
  
    <xsd:element name="migration" type="MigrationType"/>
  
    <xsd:complexType name="MigrationType">
        <xsd:choice  minOccurs="1">
            <xsd:element name="tables" type="TablesType" />
        </xsd:choice>
        <xsd:attribute name="source" type="xsd:string" use="required" />
        <xsd:attribute name="destination" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="TablesType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="table" type="TableType" />
        </xsd:choice>
    </xsd:complexType>
  
    <xsd:complexType name="TableType">
        <xsd:choice minOccurs="1">
            <xsd:element name="columns">
                <xsd:complexType>
                    <xsd:choice minOccurs="1" maxOccurs="unbounded">
                        <xsd:element name="column" type="column" />
                    </xsd:choice>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>    
        <xsd:attribute name="source" type="xsd:string" use="required" />
        <xsd:attribute name="destination" type="xsd:string" use="required" />
        <xsd:attribute name="condition" type="xsd:string" />
    </xsd:complexType>
  
    <xsd:complexType name="column">
        <xsd:attribute name="destination" use="required" />
        <xsd:attribute name="value_type">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="scalar"/>
                    <xsd:enumeration value="column" />
                    <xsd:enumeration value="timestamp" />
                    <xsd:enumeration value="expression" />
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="value" />
    </xsd:complexType>
</xsd:schema>

=== KngGroup/MySQLDataMigrator/src/ByDm/MySQLMigrateData/Tests/Loader/valid_config.xml
<?xml version="1.0" encoding="UTF-8"?>

<migration
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/bykov/NetBeansProjects/ByDmMySQLMigrateData/src/ByDm/MySQLMigrateData/Resources/migration_configuration.xsd'
    source="db1" destination="db2"
    >
    <tables>
        <table source="tab1" destination="tab2">
            <columns>
                <column destination="col1" value_type="timestamp" />
                <column destination="col2" value_type="scalar" value="3.11" />
            </columns>
        </table>
        <table source="tab3" destination="tab4">
            <columns>
                <column destination="col3" value_type="scalar" value="true" />
                <column destination="col4" value_type="scalar" value="null" />
                <column destination="col5" value="column_name" />
            </columns>
        </table>
    </tables>

</migration>
